REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\Textvp\Textvp.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Textvp\arm\gccmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Textvp\include" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\include\component" -I "D:\MyGitHub\Textvp\ResID" -I "D:\MyGitHub\Textvp\src\app\widget" -I "D:\MyGitHub\Textvp\src\app\launcher" -I "D:\MyGitHub\Textvp\src\app\wallpaper" -I "D:\MyGitHub\Textvp\src\app\screen_lock" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\include\component" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\src\framework" -I "D:\MyGitHub\Textvp\src\framework\ui_core\base" -I "D:\MyGitHub\Textvp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Textvp\src\framework\ui_core\pme" -I "D:\MyGitHub\Textvp\src\framework\mmi_core" -I "D:\MyGitHub\Textvp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Textvp\src\component" -I "D:\MyGitHub\Textvp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Textvp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Textvp\arm\Textvp.o" -c "d:\MyGitHub\Textvp\Textvp.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Textvp\include" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\include\component" -I "D:\MyGitHub\Textvp\ResID" -I "D:\MyGitHub\Textvp\src\app\widget" -I "D:\MyGitHub\Textvp\src\app\launcher" -I "D:\MyGitHub\Textvp\src\app\wallpaper" -I "D:\MyGitHub\Textvp\src\app\screen_lock" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\include\component" -I "D:\MyGitHub\Textvp\include\service" -I "D:\MyGitHub\Textvp\src\framework" -I "D:\MyGitHub\Textvp\src\framework\ui_core\base" -I "D:\MyGitHub\Textvp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Textvp\src\framework\ui_core\pme" -I "D:\MyGitHub\Textvp\src\framework\mmi_core" -I "D:\MyGitHub\Textvp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Textvp\src\component" -I "D:\MyGitHub\Textvp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Textvp"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\Textvp\Textvp.axf"  "D:\MyGitHub\Textvp\arm\gccmain.o"  "D:\MyGitHub\Textvp\arm\Textvp.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\peraudio.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percallout.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percam.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\pertcp.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perhttp.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persensor.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persim.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perrecord.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persmsper.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persmssp.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perbitstream.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percontact.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perlbs.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\permms.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perpro.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persmsmng.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\pervideo.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perxml.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persec.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perpayment.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perbt.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perpn.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perudp.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persso.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysstorage.a"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\Textvp\Textvp.pkd" -e AXF "D:\MyGitHub\Textvp\Textvp.vcproj" "D:\MyGitHub\Textvp\Textvp.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\Textvp\Textvp.vcproj" "Textvp" "0.1.0" "RDZDX" "500" "NotSupportBg" "Not Support rotate" "Textvp" "Textvp" "Textvp" "9246012102087182" "content" " Audio Call Camera TCP HTTP Sensor SIM card Record SMS(person) SMS(SP) BitStream Contact LBS MMS ProMng SMSMng Video XML Sec Payment BT PUSH UDP SysFile sso File SysStorage" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\Textvp\arm D:\MyGitHub\Textvp\build.log

